CREATE DATABASE IF NOT EXISTS patrimonio_vivo
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE patrimonio_vivo;

CREATE TABLE IF NOT EXISTS patrimonios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cidade ENUM('Antonina','Morretes') NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    nome VARCHAR(180) NOT NULL,
    inscricao VARCHAR(80) DEFAULT NULL,
    data_tombamento VARCHAR(100) DEFAULT NULL,
    localizacao VARCHAR(255) DEFAULT NULL,
    periodo VARCHAR(120) DEFAULT NULL,
    descricao TEXT NOT NULL,
    caracteristicas TEXT DEFAULT NULL,
    imagem_atual VARCHAR(500) DEFAULT NULL,
    imagem_historica VARCHAR(500) DEFAULT NULL,
    fonte_nome VARCHAR(180) NOT NULL,
    fonte_url VARCHAR(500) NOT NULL,
    fonte_imagem_atual VARCHAR(500) DEFAULT NULL,
    fonte_imagem_historica VARCHAR(500) DEFAULT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO patrimonios
(cidade, slug, nome, inscricao, data_tombamento, localizacao, periodo, descricao, caracteristicas, imagem_atual, imagem_historica, fonte_nome, fonte_url, fonte_imagem_atual, fonte_imagem_historica)
VALUES

('Antonina',
 'pilar',
 'Igreja de Nossa Senhora do Pilar',
 '122-II',
 '08 de novembro de 1999',
 'Praça Coronel Macedo – Centro, Antonina/PR',
 'Mais de três séculos de história',
 'Uma das edificações religiosas mais antigas do Paraná. A capela-mor foi inaugurada em 1715 e a construção foi ampliada ao longo do tempo. Desde 1999, é bem cultural tombado pelo Estado do Paraná e, desde 2012, integra o tombamento do Centro Histórico de Antonina pelo IPHAN.',
 'Arquitetura religiosa histórica; núcleo inicial da antiga Freguesia de Nossa Senhora do Pilar.',
 './img/antonina/pilar/atual.jpg',
 NULL,
 'Patrimônio Cultural do Paraná',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Igreja-da-Nossa-Senhora-do-Pilar-Antonina',
 'https://commons.wikimedia.org/wiki/Category:Igreja_de_Nossa_Senhora_do_Pilar_(Antonina)',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Igreja-da-Nossa-Senhora-do-Pilar-Antonina'),

('Antonina',
 'estacao-ferroviaria',
 'Estação Ferroviária de Antonina',
 '173-II',
 '28 de agosto de 2012',
 'Rua Uruguai, Antonina/PR',
 'Final do século XIX / início do século XX',
 'A primeira estação, construída em madeira, foi inaugurada em 1892. A sede atual, em alvenaria, data de 1916. O conjunto está ligado à expansão ferroviária do Paraná, ao antigo ramal Morretes–Antonina e às atividades portuárias e comerciais do município.',
 'Patrimônio ferroviário; relação com circulação econômica, integração territorial e desenvolvimento urbano.',
 './img/antonina/estacao/atual.jpg',
 NULL,
 'Patrimônio Cultural do Paraná',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Estacao-Ferroviaria-de-Antonina',
 'https://commons.wikimedia.org/wiki/Category:Estação_Ferroviária_de_Antonina',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Estacao-Ferroviaria-de-Antonina'),

('Antonina',
 'sao-benedito',
 'Igreja São Benedito',
 NULL,
 'Integra o Centro Histórico de Antonina, tombado pelo IPHAN em 2012',
 'Rua XV de Novembro, 150 – Centro, Antonina/PR',
 'Construção secular',
 'Igreja de características históricas e coloniais que integra o Centro Histórico de Antonina. Em 2026, o IPHAN registrou obras de restauração financiadas pelo Novo PAC, com conclusão prevista para fevereiro de 2027.',
 'Características coloniais; relação com a memória religiosa e cultural de Antonina.',
 './img/antonina/sao-benedito/atual.jpg',
 NULL,
 'IPHAN / Prefeitura de Antonina',
 'https://www.gov.br/iphan/pt-br/assuntos/noticias/iphan-fiscaliza-obras-de-restauracao-na-igreja-sao-benedito-em-antonina-pr',
 'https://commons.wikimedia.org/wiki/File:Igreja_Matriz_de_Antonina4.JPG',
 'https://www.gov.br/iphan/pt-br/assuntos/noticias/iphan-fiscaliza-obras-de-restauracao-na-igreja-sao-benedito-em-antonina-pr'),

('Morretes',
 'rocha-pombo',
 'Casa Rocha Pombo',
 '40-II',
 '19 de julho de 1973',
 'Largo Dr. José Pereira, 43 – Morretes/PR',
 'Construção de data não determinada',
 'Casa em que nasceu José Francisco da Rocha Pombo. A documentação oficial informa que não existem elementos precisos sobre o ano em que a casa foi construída. O imóvel foi restaurado pelo Governo do Paraná e pela Prefeitura de Morretes e adaptado para serviços de biblioteca municipal.',
 'Moradia de um pavimento em alvenaria mista de pedra e tijolos; duas frentes; vergas em arco semicircular; janelas de guilhotina; cobertura de quatro águas com telha capa-e-canal.',
 './img/morretes/rocha-pombo/atual.jpg',
 NULL,
 'Patrimônio Cultural do Paraná',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Casa-Rocha-Pombo-Morretes',
 'https://commons.wikimedia.org/wiki/File:Rocha_Pombo_Casa.jpg',
 'https://www.patrimoniocultural.pr.gov.br/Galeria-de-Imagens/Casa-Rocha-Pombo-Morretes'),

('Morretes',
 'sao-sebastiao',
 'Igreja de São Sebastião de Porto de Cima',
 '3-II',
 '14 de março de 1963',
 'Porto de Cima – Morretes/PR',
 'Século XVIII e ampliações posteriores',
 'Com mais de dois séculos de história, a igreja testemunhou a colonização luso-brasileira da região. A construção de uma capela sob a invocação de Nossa Senhora da Guia e São Sebastião foi iniciada em 1779. A ampliação posterior deixou duas fachadas como testemunho de diferentes etapas da história do edifício.',
 'Duas fachadas; frontão triangular; elementos decorativos associados à fase mais antiga; localização em frente à praça principal de Porto de Cima, às margens do Rio Nhundiaquara.',
 './img/morretes/sao-sebastiao/atual.jpg',
 NULL,
 'Patrimônio Cultural do Paraná',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Igreja-de-Sao-Sebastiao-de-Porto-de-Cima-Morretes',
 'https://commons.wikimedia.org/wiki/File:Igreja_de_São_Sebastião_do_Porto_de_Cima.jpg',
 'https://www.patrimoniocultural.pr.gov.br/Bem-Tombado/Igreja-de-Sao-Sebastiao-de-Porto-de-Cima-Morretes'),

('Morretes',
 'conjunto-historico',
 'Conjunto Histórico, Urbanístico e Paisagístico de Morretes',
 '28-I e 180-II',
 '18 de julho de 2022',
 'Área central de Morretes/PR',
 'Formação histórica do litoral paranaense',
 'O conjunto reúne uma paisagem urbana representativa da formação histórica do litoral paranaense, às margens do Rio Nhundiaquara e ao sopé da Serra do Mar. Preserva relações entre natureza, caminhos coloniais, arquitetura, ferrovia, comércio, navegação fluvial e modos tradicionais de ocupação.',
 'Paisagem urbana histórica; arquitetura civil e religiosa; relação entre cidade, rio, serra e caminhos históricos.',
 './img/morretes/conjunto-historico/atual.jpg',
 NULL,
 'Patrimônio Cultural do Paraná',
 'https://www.patrimoniocultural.pr.gov.br/Pagina/28-I-e-180-II-Conjunto-Historico-Urbanistico-e-Paisagistico-de-Morretes',
 'https://commons.wikimedia.org/wiki/Category:Morretes',
 'https://www.patrimoniocultural.pr.gov.br/Pagina/28-I-e-180-II-Conjunto-Historico-Urbanistico-e-Paisagistico-de-Morretes');
